In [1]:
import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path.cwd().parent / "src"))

from ingesta.CargadorDatos import CargadorDatos
from gestor.GestorPartidos import GestorPartidos

In [2]:
cargador = CargadorDatos(
    url_source="https://raw.githubusercontent.com/martj42/international_results/master/results.csv",
    raw_path="../data/raw",
    processed_path="../data/processed",
)
df_final = cargador.ejecutar()

gestor = GestorPartidos(df_final)
resultado = gestor.get_por_equipo("Brazil")
print(resultado.shape)
#print(resultado.tail(30))
resultado.head()

INFO:ingesta.CargadorDatos:Descargando CSV desde https://raw.githubusercontent.com/martj42/international_results/master/results.csv
INFO:ingesta.CargadorDatos:Descarga completa, dimension de: 49503 filas y 9 columnas
INFO:ingesta.CargadorDatos:Filtro aplicado para 'FIFA World Cup': 1062 filas
WARNING:ingesta.CargadorDatos:Se encontraron 12 valores nulos en marcadores
INFO:ingesta.CargadorDatos:Guardado raw en: ..\data\raw\raw_results.csv
INFO:ingesta.CargadorDatos:Guardado processed en: ..\data\raw\partidos-mundial.csv

(119, 10)

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,clave_partido
1492,1930-07-14,Brazil,Yugoslavia,1.0,2.0,FIFA World Cup,Montevideo,Uruguay,True,1930-07-14_Brazil_Yugoslavia
1503,1930-07-20,Bolivia,Brazil,0.0,4.0,FIFA World Cup,Montevideo,Uruguay,True,1930-07-20_Bolivia_Brazil
1880,1934-05-27,Brazil,Spain,1.0,3.0,FIFA World Cup,Genoa,Italy,True,1934-05-27_Brazil_Spain
2329,1938-06-05,Brazil,Poland,6.0,5.0,FIFA World Cup,Strasbourg,France,True,1938-06-05_Brazil_Poland
2339,1938-06-12,Brazil,Czechoslovakia,1.0,1.0,FIFA World Cup,Bordeaux,France,True,1938-06-12_Brazil_Czechoslovakia

In [3]:
anio = gestor.get_por_anio(1938)
print(anio)

sede = gestor.get_por_sede('Brazil')
print(sede)

           date       home_team       away_team  home_score  away_score  \
2328 1938-06-04         Germany     Switzerland         1.0         1.0
2329 1938-06-05          Brazil          Poland         6.0         5.0
2330 1938-06-05            Cuba         Romania         3.0         3.0
2331 1938-06-05  Czechoslovakia     Netherlands         3.0         0.0
2332 1938-06-05          France         Belgium         3.0         1.0
2333 1938-06-05         Hungary       Indonesia         6.0         0.0
2334 1938-06-05           Italy          Norway         2.0         1.0
2335 1938-06-09            Cuba         Romania         2.0         1.0
2336 1938-06-09         Germany     Switzerland         2.0         4.0
2339 1938-06-12          Brazil  Czechoslovakia         1.0         1.0
2340 1938-06-12            Cuba          Sweden         0.0         8.0
2341 1938-06-12          France           Italy         1.0         3.0
2342 1938-06-12         Hungary     Switzerland         2.0         0.0
2343 1938-06-14          Brazil  Czechoslovakia         2.0         1.0
2345 1938-06-16          Brazil           Italy         1.0         2.0
2346 1938-06-16         Hungary          Sweden         5.0         1.0
2349 1938-06-19          Brazil          Sweden         4.0         2.0
2350 1938-06-19         Hungary           Italy         2.0         4.0

          tournament        city country  neutral  \
2328  FIFA World Cup       Paris  France     True
2329  FIFA World Cup  Strasbourg  France     True
2330  FIFA World Cup    Toulouse  France     True
2331  FIFA World Cup    Le Havre  France     True
2332  FIFA World Cup    Colombes  France    False
2333  FIFA World Cup       Reims  France     True
2334  FIFA World Cup   Marseille  France     True
2335  FIFA World Cup    Toulouse  France     True
2336  FIFA World Cup       Paris  France     True
2339  FIFA World Cup    Bordeaux  France     True
2340  FIFA World Cup     Antibes  France     True
2341  FIFA World Cup    Colombes  France    False
2342  FIFA World Cup       Lille  France     True
2343  FIFA World Cup    Bordeaux  France     True
2345  FIFA World Cup   Marseille  France     True
2346  FIFA World Cup       Paris  France     True
2349  FIFA World Cup    Bordeaux  France     True
2350  FIFA World Cup    Colombes  France     True

                              clave_partido
2328         1938-06-04_Germany_Switzerland
2329               1938-06-05_Brazil_Poland
2330                1938-06-05_Cuba_Romania
2331  1938-06-05_Czechoslovakia_Netherlands
2332              1938-06-05_France_Belgium
2333           1938-06-05_Hungary_Indonesia
2334                1938-06-05_Italy_Norway
2335                1938-06-09_Cuba_Romania
2336         1938-06-09_Germany_Switzerland
2339       1938-06-12_Brazil_Czechoslovakia
2340                 1938-06-12_Cuba_Sweden
2341                1938-06-12_France_Italy
2342         1938-06-12_Hungary_Switzerland
2343       1938-06-14_Brazil_Czechoslovakia
2345                1938-06-16_Brazil_Italy
2346              1938-06-16_Hungary_Sweden
2349               1938-06-19_Brazil_Sweden
2350               1938-06-19_Hungary_Italy
            date    home_team      away_team  home_score  away_score  \
3391  1950-06-24       Brazil         Mexico         4.0         0.0
3393  1950-06-25        Chile        England         0.0         2.0
3395  1950-06-25        Italy         Sweden         2.0         3.0
3396  1950-06-25        Spain  United States         3.0         1.0
3397  1950-06-25  Switzerland     Yugoslavia         0.0         3.0
...          ...          ...            ...         ...         ...
37926 2014-07-05  Netherlands     Costa Rica         0.0         0.0
37928 2014-07-08       Brazil        Germany         1.0         7.0
37929 2014-07-09  Netherlands      Argentina         0.0         0.0
37931 2014-07-12       Brazil    Netherlands         0.0         3.0
37933 2014-07-13      Germany      Argentina         1.0         0.0

           tournament            city country  neutral  \
3391   FIFA World Cup  Rio de Janeiro  Brazil    False
3393   FIFA World Cup  Rio de Janeiro  Brazil     True
3395   FIFA World Cup       São Paulo  Brazil     True
3396   FIFA World Cup        Curitiba  Brazil     True
3397   FIFA World Cup  Belo Horizonte  Brazil     True
...               ...             ...     ...      ...
37926  FIFA World Cup        Salvador  Brazil     True
37928  FIFA World Cup  Belo Horizonte  Brazil    False
37929  FIFA World Cup       São Paulo  Brazil     True
37931  FIFA World Cup        Brasília  Brazil    False
37933  FIFA World Cup  Rio de Janeiro  Brazil     True

                           clave_partido
3391            1950-06-24_Brazil_Mexico
3393            1950-06-25_Chile_England
3395             1950-06-25_Italy_Sweden
3396      1950-06-25_Spain_United States
3397   1950-06-25_Switzerland_Yugoslavia
...                                  ...
37926  2014-07-05_Netherlands_Costa Rica
37928          2014-07-08_Brazil_Germany
37929   2014-07-09_Netherlands_Argentina
37931      2014-07-12_Brazil_Netherlands
37933       2014-07-13_Germany_Argentina

[86 rows x 10 columns]

In [4]:
resultado = gestor.ventaja_local()
resultado

,date,home_team,away_team,home_score,away_score,city,country
1499,1930-07-18,Uruguay,Peru,1.0,0.0,Montevideo,Uruguay
1504,1930-07-21,Uruguay,Romania,4.0,0.0,Montevideo,Uruguay
1508,1930-07-27,Uruguay,Yugoslavia,6.0,1.0,Montevideo,Uruguay
1509,1930-07-30,Uruguay,Argentina,4.0,2.0,Montevideo,Uruguay
1883,1934-05-27,Italy,United States,7.0,1.0,Rome,Italy
1888,1934-05-31,Italy,Spain,1.0,1.0,Florence,Italy
1889,1934-06-01,Italy,Spain,1.0,0.0,Florence,Italy
1891,1934-06-03,Italy,Austria,1.0,0.0,Milan,Italy
1894,1934-06-10,Italy,Czechoslovakia,2.0,1.0,Rome,Italy
2332,1938-06-05,France,Belgium,3.0,1.0,Colombes,France
2341,1938-06-12,France,Italy,1.0,3.0,Colombes,France
3391,1950-06-24,Brazil,Mexico,4.0,0.0,Rio de Janeiro,Brazil
3398,1950-06-28,Brazil,Switzerland,2.0,2.0,São Paulo,Brazil
3403,1950-07-01,Brazil,Yugoslavia,2.0,0.0,Rio de Janeiro,Brazil
3411,1950-07-09,Brazil,Sweden,7.0,1.0,Rio de Janeiro,Brazil
3415,1950-07-13,Brazil,Spain,6.0,1.0,Rio de Janeiro,Brazil
3417,1950-07-16,Brazil,Uruguay,1.0,2.0,Rio de Janeiro,Brazil
3963,1954-06-17,Switzerland,Italy,2.0,1.0,Lausanne,Switzerland
3971,1954-06-20,Switzerland,England,0.0,2.0,Bern,Switzerland
3973,1954-06-23,Switzerland,Italy,4.0,1.0,Basel,Switzerland
3975,1954-06-26,Switzerland,Austria,5.0,7.0,Lausanne,Switzerland
4703,1958-06-08,Sweden,Mexico,3.0,0.0,Solna,Sweden
4711,1958-06-12,Sweden,Hungary,2.0,1.0,Solna,Sweden
4720,1958-06-15,Sweden,Wales,0.0,0.0,Solna,Sweden
4727,1958-06-19,Sweden,Russia,2.0,0.0,Solna,Sweden
4729,1958-06-24,Sweden,Germany,3.0,1.0,Gothenburg,Sweden
4733,1958-06-29,Sweden,Brazil,2.0,5.0,Solna,Sweden
5503,1962-05-30,Chile,Switzerland,3.0,1.0,Santiago,Chile
5511,1962-06-02,Chile,Italy,2.0,0.0,Santiago,Chile
5522,1962-06-06,Chile,Germany,0.0,2.0,Santiago,Chile
5530,1962-06-10,Chile,Russia,2.0,1.0,Arica,Chile
5534,1962-06-13,Chile,Brazil,2.0,4.0,Santiago,Chile
5536,1962-06-16,Chile,Yugoslavia,1.0,0.0,Santiago,Chile
6696,1966-07-11,England,Uruguay,0.0,0.0,London,England
6710,1966-07-16,England,Mexico,2.0,0.0,London,England
6719,1966-07-20,England,France,2.0,0.0,London,England
6722,1966-07-23,England,Argentina,1.0,0.0,London,England
6727,1966-07-26,England,Portugal,2.0,1.0,London,England
6729,1966-07-30,England,Germany,4.0,2.0,London,England
8057,1970-05-31,Mexico,Russia,0.0,0.0,Mexico City,Mexico
8074,1970-06-07,Mexico,El Salvador,4.0,0.0,Mexico City,Mexico
8082,1970-06-11,Mexico,Belgium,1.0,0.0,Mexico City,Mexico
8086,1970-06-14,Mexico,Italy,1.0,4.0,Toluca,Mexico
9771,1974-06-14,Germany,Chile,1.0,0.0,Berlin,Germany
9777,1974-06-18,Germany,Australia,3.0,0.0,Hamburg,Germany
9786,1974-06-22,Germany,German DR,0.0,1.0,Hamburg,Germany
9793,1974-06-26,Germany,Yugoslavia,2.0,0.0,Düsseldorf,Germany
9799,1974-06-30,Germany,Sweden,4.0,2.0,Düsseldorf,Germany
9803,1974-07-03,Germany,Poland,1.0,0.0,Frankfurt,Germany
9809,1974-07-07,Germany,Netherlands,2.0,1.0,Munich,Germany
11382,1978-06-02,Argentina,Hungary,2.0,1.0,Buenos Aires,Argentina
11389,1978-06-06,Argentina,France,2.0,1.0,Buenos Aires,Argentina
11397,1978-06-10,Argentina,Italy,0.0,1.0,Buenos Aires,Argentina
11408,1978-06-14,Argentina,Poland,2.0,0.0,Rosario,Argentina
11416,1978-06-18,Argentina,Brazil,0.0,0.0,Rosario,Argentina
11421,1978-06-21,Argentina,Peru,6.0,0.0,Rosario,Argentina
11430,1978-06-25,Argentina,Netherlands,3.0,1.0,Buenos Aires,Argentina
13308,1982-06-16,Spain,Honduras,1.0,1.0,Valencia,Spain
13320,1982-06-20,Spain,Yugoslavia,2.0,1.0,Valencia,Spain
13336,1982-06-25,Spain,Northern Ireland,0.0,1.0,Valencia,Spain
13347,1982-07-02,Spain,Germany,1.0,2.0,Madrid,Spain
13351,1982-07-05,Spain,England,0.0,0.0,Madrid,Spain
15327,1986-06-03,Mexico,Belgium,2.0,1.0,Mexico City,Mexico
15341,1986-06-07,Mexico,Paraguay,1.0,1.0,Mexico City,Mexico
15354,1986-06-11,Mexico,Iraq,1.0,0.0,Mexico City,Mexico
15362,1986-06-15,Mexico,Bulgaria,2.0,0.0,Mexico City,Mexico
15372,1986-06-21,Mexico,Germany,0.0,0.0,Monterrey,Mexico
17324,1990-06-09,Italy,Austria,1.0,0.0,Rome,Italy
17338,1990-06-14,Italy,United States,1.0,0.0,Rome,Italy
17352,1990-06-19,Italy,Czechoslovakia,2.0,0.0,Rome,Italy
17365,1990-06-25,Italy,Uruguay,2.0,0.0,Rome,Italy
17368,1990-06-30,Italy,Republic of Ireland,1.0,0.0,Rome,Italy
17372,1990-07-03,Italy,Argentina,1.0,1.0,Naples,Italy
17375,1990-07-07,Italy,England,2.0,1.0,Bari,Italy
19769,1994-06-18,United States,Switzerland,1.0,1.0,Pontiac,United States
19779,1994-06-22,United States,Colombia,2.0,1.0,Pasadena,United States
19791,1994-06-26,United States,Romania,0.0,1.0,Pasadena,United States
19810,1994-07-04,United States,Brazil,0.0,1.0,Palo Alto,United States
22828,1998-06-12,France,South Africa,3.0,0.0,Marseille,France
22845,1998-06-18,France,Saudi Arabia,4.0,0.0,Saint-Denis,France
22863,1998-06-24,France,Denmark,2.0,1.0,Lyon,France
22882,1998-06-28,France,Paraguay,1.0,0.0,Lens,France
22891,1998-07-03,France,Italy,0.0,0.0,Saint-Denis,France
22898,1998-07-08,France,Croatia,2.0,1.0,Saint-Denis,France
22903,1998-07-12,France,Brazil,3.0,0.0,Saint-Denis,France
26448,2002-06-04,Japan,Belgium,2.0,2.0,Saitama,Japan
26449,2002-06-04,South Korea,Poland,2.0,0.0,Busan,South Korea
26466,2002-06-09,Japan,Russia,1.0,0.0,Yokohama,Japan
26469,2002-06-10,South Korea,United States,1.0,1.0,Daegu,South Korea
26485,2002-06-14,Japan,Tunisia,2.0,0.0,Osaka,Japan
26486,2002-06-14,South Korea,Portugal,1.0,0.0,Incheon,South Korea
26494,2002-06-18,Japan,Turkey,0.0,1.0,Rifu,Japan
26495,2002-06-18,South Korea,Italy,2.0,1.0,Daejeon,South Korea
26499,2002-06-22,South Korea,Spain,0.0,0.0,Gwangju,South Korea
26502,2002-06-25,South Korea,Germany,0.0,1.0,Seoul,South Korea
26505,2002-06-29,South Korea,Turkey,2.0,3.0,Daegu,South Korea
30037,2006-06-09,Germany,Costa Rica,4.0,2.0,Munich,Germany
30051,2006-06-14,Germany,Poland,1.0,0.0,Dortmund,Germany
30070,2006-06-20,Germany,Ecuador,3.0,0.0,Berlin,Germany
30086,2006-06-24,Germany,Sweden,2.0,0.0,Munich,Germany
30099,2006-06-30,Germany,Argentina,1.0,1.0,Berlin,Germany
30105,2006-07-04,Germany,Italy,0.0,2.0,Dortmund,Germany
30109,2006-07-08,Germany,Portugal,3.0,1.0,Stuttgart,Germany
33864,2010-06-11,South Africa,Mexico,1.0,1.0,Johannesburg,South Africa
33879,2010-06-16,South Africa,Uruguay,0.0,3.0,Pretoria,South Africa
33905,2010-06-22,South Africa,France,2.0,1.0,Bloemfontein,South Africa
37861,2014-06-12,Brazil,Croatia,3.0,1.0,São Paulo,Brazil
37876,2014-06-17,Brazil,Mexico,0.0,0.0,Fortaleza,Brazil
37897,2014-06-23,Brazil,Cameroon,4.0,1.0,Brasília,Brazil
37913,2014-06-28,Brazil,Chile,1.0,1.0,Belo Horizonte,Brazil
37923,2014-07-04,Brazil,Colombia,2.0,1.0,Fortaleza,Brazil
37928,2014-07-08,Brazil,Germany,1.0,7.0,Belo Horizonte,Brazil
37931,2014-07-12,Brazil,Netherlands,0.0,3.0,Brasília,Brazil
41639,2018-06-14,Russia,Saudi Arabia,5.0,0.0,Moscow,Russia
41655,2018-06-19,Russia,Egypt,3.0,1.0,Saint Petersburg,Russia
41671,2018-06-25,Russia,Uruguay,0.0,3.0,Samara,Russia
41689,2018-07-01,Russia,Spain,1.0,1.0,Moscow,Russia
41699,2018-07-07,Russia,Croatia,2.0,2.0,Sochi,Russia
45717,2022-11-20,Qatar,Ecuador,0.0,2.0,Al Khor,Qatar
45733,2022-11-25,Qatar,Senegal,1.0,3.0,Doha,Qatar
45750,2022-11-29,Qatar,Netherlands,0.0,2.0,Al Khor,Qatar
49405,2026-06-11,Mexico,South Africa,2.0,0.0,Mexico City,Mexico
49407,2026-06-12,Canada,Bosnia and Herzegovina,1.0,1.0,Toronto,Canada
49408,2026-06-12,United States,Paraguay,4.0,1.0,Inglewood,United States
49430,2026-06-18,Mexico,South Korea,1.0,0.0,Zapopan,Mexico
49432,2026-06-18,Canada,Qatar,6.0,0.0,Vancouver,Canada
49435,2026-06-19,United States,Australia,2.0,0.0,Seattle,United States
49453,2026-06-24,Mexico,Czech Republic,3.0,0.0,Mexico City,Mexico
49455,2026-06-24,Canada,Switzerland,1.0,2.0,Vancouver,Canada
49459,2026-06-25,United States,Turkey,2.0,3.0,Inglewood,United States
49483,2026-06-30,Mexico,Ecuador,2.0,0.0,Mexico City,Mexico
49486,2026-07-01,United States,Bosnia and Herzegovina,2.0,0.0,Santa Clara,United States
49496,2026-07-05,Mexico,England,2.0,3.0,Mexico City,Mexico